# Site settings
title: Barry Richards
email: barry@br-web.io
description:
   Front-end developer and UI designer currently available for hire.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
port: 4000
livereload: true

include: ["_pages"]