# Site settings
title: Barry Richards
email: barry@br-web.io
description: Front-end developer and UI designer currently available for hire.
baseurl: ""
url: "https://bazzle.github.io/portfolio/"
# Build settings
markdown: kramdown
port: 4000
livereload: false
include: ["_pages"]